### ISSUE TITLE
dreambooth support

### ISSUE THREAD

**Issue by ghost** [albarji/mixture-of-diffusers#14]
does this work with dreambooth?

**Comment by ghost** [comment]
image to image to combine 2-3 photos would also be rad

but not sure how well these models overlap

surprised this design hasn't been picked up officially by diffusers

**Comment by albarji** [comment]
Hi there! Any model checkpoint that is derived from Stable Diffusion 1.5 should work. So you could train a Dreambooth model with other tools and then use it here. But I recommend using the [multidiffusion upscaler plugin](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) for the automatic1111 UI.

About using more than one model in the same image, this is theoretically possible as long as your GPU is big enough to keep all those models in memory. Although this feature is not currently supported by this code, you could tweat with it to be able to do so.

**Comment by ghost** [comment]
thanks for the response!
