### ISSUE TITLE
Is this compatible with MultiDiffusion?

### ISSUE THREAD

**Issue by Njasa2k** [albarji/mixture-of-diffusers#6]
Is this compatible with MultiDiffusion?
https://github.com/omerbt/MultiDiffusion

**Comment by albarji** [comment]
In all honesty, I wasn't aware of that project. It seems it tries to achieve the same goal as Mixture of Diffusers, though using a different technique, but I haven't had the time to read their paper in full detail.

Anyway, the answer is: no, this project is not compatible with MultiDiffusion.
